In [95]:
import numpy as np # import library yang dibutuhkan

1. Membuat Tensor

In [96]:
a = [[23,50],[7,12]]
b = [[57,67],[99,43]]
c = [[75,21],[57,12]]
d = [[87,26],[18,84]]

In [97]:
tensor = np.array([a,b,c,d])

In [98]:
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [99]:
tensor.shape

(4, 2, 2)

In [100]:
tensor.ndim

3

2. Melakukan Perkalian Matrix A dan B

In [101]:
A = [23,50,19,7,12,109,57,67,98]
A = np.array(A).reshape(3,3)
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [102]:
B = [17,22,19]
B = np.array(B).reshape(3,1)
B

array([[17],
       [22],
       [19]])

In [103]:
A@B

array([[1852],
       [2454],
       [4305]])

In [104]:
A*B

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

In [105]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

3. Melakukan transpose Matrix A

In [106]:
A.T #transpose matrix

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])