In [35]:
import numpy as np
from numpy.linalg import eig,inv

In [36]:
v1 = [1,3]
v2 = [1,-1,6,4]
v1 = np.array(v1).reshape(2,1)
v2 = np.array(v2).reshape(2,2)

Membuktikan apakah matrix v1 merupakan eigen vector dari matrix v2

In [37]:
v1

array([[1],
       [3]])

In [38]:
v2

array([[ 1, -1],
       [ 6,  4]])

In [39]:
eigVal, eigVec = eig(v2) 

In [40]:
eigVal.real # eigen vector v1

array([2.5, 2.5])

Mencari eigen vector v2

In [41]:
eigVec.real # eigen vector v2

array([[ 0.23145502,  0.23145502],
       [-0.9258201 , -0.9258201 ]])

Pembuktian rekonstruksi matrix

In [42]:
eigVec.dot(np.diag(eigVal)).dot(inv(eigVec)).real #matrix reconstruction

array([[ 1., -1.],
       [ 6.,  4.]])

Kesimpulan: matrix v1 bukan eigen vector dari matrix v2
karena eigen vector dari matrix v2 adalah berikut:

In [43]:
eigVec.real # eigen vector v2

array([[ 0.23145502,  0.23145502],
       [-0.9258201 , -0.9258201 ]])